{"uuid": "7f307638-dbf0-411f-839b-46aaec2c48ad", "children": ["66ef50be-7849-4e92-bfc5-4ced5491c984"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"d:\\tool\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\tool\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\tool\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"d:\\tool\\python\\lib\\site-packages\\_pytest\\python.py\", line 701, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"d:\\tool\\python\\lib\\site-packages\\_pytest\\python.py\", line 632, in _call_with_optional_argument\n    func(arg)\n  File \"E:\\01授课工作区\\online_uitest\\UI_TEST_DAY14\\Hmtt_Ui_Test\\case\\mp\\test_mp_login.py\", line 14, in setup_class\n    self.driver = DriverUtils.get_mp_driver()\n  File \"E:\\01授课工作区\\online_uitest\\UI_TEST_DAY14\\Hmtt_Ui_Test\\utils.py\", line 35, in get_mp_driver\n    chrome_options=chrome_options)\n  File \"d:\\tool\\python\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"d:\\tool\\python\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1598575382430, "stop": 1598575382432}], "start": 1598575382430, "stop": 1598575382533}